PierreBakery3/Models/Flavor.cs
using System.Collections.Generic;

namespace Bakery.Models
{
  public class Flavor
  {
    public Flavor()
    {
      JoinEntities = new HashSet<FlavorTreat>();
    }
    public int FlavorId {get; set;}
    public string FlavorName {get; set;}
    public virtual ApplicationUser User {get; set;}
    public virtual ICollection<FlavorTreat> JoinEntities {get;}
  }
}

PierreBakery3/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Bakery.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly BakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public FlavorsController(UserManager<ApplicationUser> userManager, BakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public async Task<ActionResult> Create (Flavor flavor)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      flavor.User = currentUser;
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var model = _db.Flavors
      .Include(treat => treat.JoinEntities)
      .ThenInclude(join => join.Flavor)
      .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(model);
    }
    public ActionResult Edit(int id)
    {
      var model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(model);
    }
    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult Delete(int id)
    {
      var model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(model);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var deleted = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(deleted);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult AddTreat(int id)
    {
      var model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "TreatName");
      return View(model);
    }
    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      var check = _db.FlavorTreat.FirstOrDefault(entry => entry.TreatId == TreatId && entry.FlavorId == flavor.FlavorId);
      if (TreatId != 0 && check == null)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
  }
}

PierreBakery3/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Bakery.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly BakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public TreatsController(UserManager<ApplicationUser> userManager, BakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public ActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public async Task<ActionResult> Create (Treat treat)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      treat.User = currentUser;
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      var model = _db.Treats
      .Include(flavor=> flavor.JoinEntities)
      .ThenInclude(join => join.Flavor)
      .FirstOrDefault(treat => treat.TreatId == id);
      return View(model);
    }
    public ActionResult AddFlavor(int id)
    {
      var model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorName");
      return View(model);
    }
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int FlavorId)
    {
      var check = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorId == FlavorId && entry.TreatId == treat.TreatId);
      if (FlavorId != 0 && check == null )
      {
      _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult Edit(int id)
    {
      var model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(model);
    }
    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
    public ActionResult Delete(int id)
    {
      var model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(model);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var deleted = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(deleted);
      _db.SaveChanges();
      return RedirectToAction("Index", "Home");
    }
  }
}

PierreBakery3/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h2>Add a Treat to @Html.DisplayFor(model=> model.FlavorName) </h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.Label("Select treat")
    @Html.DropDownList("TreatId")

    <input type="submit" value="Add Treat" class="btn btn-info btn-sm" />
}

<p>@Html.ActionLink("Go back to Details", "Details", new { id = Model.FlavorId })</p>

PierreBakery3/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}
@model Bakery.Models.Flavor

<h4> Add a new Flavor</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.FlavorName)
    @Html.TextBoxFor(model => model.FlavorName)

    <input type="submit" value="Add new Flavor" class="btn btn-info btn-sm" />
}

PierreBakery3/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Bakery.Models.Flavor

<h2>Are you sure you want to delete @Html.DisplayFor(model => model.FlavorName)</h2>
@using (Html.BeginForm())
{
  <button class="btn btn-danger btn-sm" type="submit">Delete</button>
}

<p>@Html.ActionLink("Go back to Details", "Details", new { id = Model.FlavorId })</p>

PierreBakery3/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@using Bakery.Models;
@model Flavor;

<h2>Flavor Details</h2>
<p>---</p>
<h3>Name: @Html.DisplayFor(model => model.FlavorName)</h3>
<h3>Treats Available in this Flavor:</h3>
@if(@Model.JoinEntities.Count == 0)
{
  <p>No Treats added</p>
}
else
{
  <ul>
  @foreach (FlavorTreat element in Model.JoinEntities)
  {
    <li>@Html.ActionLink($"{element.Treat.TreatName}", "Details", "Treats",new {id = element.TreatId})</li>
    @if (User.Identity.IsAuthenticated)
    {
      @using (Html.BeginForm("DeleteTreat", "Flavors"))
      {
        @Html.Hidden("joinId", @element.FlavorTreatId)
        <button class="btn btn-danger btn-sm" type="submit">Delete</button>
      }
    }
  }
  </ul>
}
@if (User.Identity.IsAuthenticated)
{
<button class="btn btn-danger btn-sm" onclick="location.href='@Url.Action("Delete", new {id = Model.FlavorId})'">Delete this Flavor</button> 
<button class="btn btn-warning btn-sm" onclick="location.href='@Url.Action("Edit", new {id = Model.FlavorId})'">Edit this Flavor</button> 
<button class="btn btn-warning btn-sm" onclick="location.href='@Url.Action("AddTreat", new {id = Model.FlavorId})'">Add Treat to this Flavor</button> 
}

PierreBakery3/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}
@using Bakery.Models;
@model Flavor 

<h2>Edit</h2>

<h4>Edit @Html.DisplayFor(model => model.FlavorName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.FlavorId)

    @Html.LabelFor(model => model.FlavorName)
    @Html.EditorFor(model => model.FlavorName)

    <input type="submit" value="Save Flavor" class="btn btn-info btn-sm" />
}